# coding: utf-8

"""
    REST API Mapy.cz geocoding methods

    Get coordinates and location for given geographic entity (e.g. address, city, WGS coordinates)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mapy_cz_geocode.models.geocode_entity_type import GeocodeEntityType  # noqa: E501

class TestGeocodeEntityType(unittest.TestCase):
    """GeocodeEntityType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeocodeEntityType(self):
        """Test GeocodeEntityType"""
        # inst = GeocodeEntityType()

if __name__ == '__main__':
    unittest.main()
