# coding: utf-8

"""
    REST API Mapy.cz geocoding methods

    Get coordinates and location for given geographic entity (e.g. address, city, WGS coordinates)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from mapy_cz_geocode.models.coordinates import Coordinates  # noqa: E501

class TestCoordinates(unittest.TestCase):
    """Coordinates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Coordinates:
        """Test Coordinates
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Coordinates`
        """
        model = Coordinates()  # noqa: E501
        if include_optional:
            return Coordinates(
                lon = 14.42212,
                lat = 50.08861
            )
        else:
            return Coordinates(
                lon = 14.42212,
                lat = 50.08861,
        )
        """

    def testCoordinates(self):
        """Test Coordinates"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
