# coding: utf-8

"""
    REST API Mapy.cz geocoding methods

    Get coordinates and location for given geographic entity (e.g. address, city, WGS coordinates)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class Language(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    CS = 'cs'
    DE = 'de'
    EL = 'el'
    EN = 'en'
    ES = 'es'
    FR = 'fr'
    IT = 'it'
    NL = 'nl'
    PL = 'pl'
    PT = 'pt'
    RU = 'ru'
    SK = 'sk'
    TR = 'tr'
    UK = 'uk'

    @classmethod
    def from_json(cls, json_str: str) -> Language:
        """Create an instance of Language from a JSON string"""
        return Language(json.loads(json_str))


